OUTPUT_DIR: '/edward-slow-vol/checkpoints/smd_new_1/'
DATA:
  TRAIN:
    SIM:
      ROOT_DIR: "/messytable-slow-vol/messy-table-dataset/v12_sample/training"
      SPLIT_FILE: "/messytable-slow-vol/messy-table-dataset/v12_sample/training_lists/all_train.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "0128_irL_kuafu_half.png"
      RIGHT_NAME: "0128_irR_kuafu_half.png"
      LEFT_PATTERN_NAME: "0128_irL_kuafu_half.png"
      RIGHT_PATTERN_NAME: "0128_irR_kuafu_half.png"
      DEPTH_R_NAME: "depthR.png"
    REAL:
      ROOT_DIR: "/messytable-slow-vol/messy-table-dataset/rand_scenes/rand_scenes"
      SPLIT_FILE: "/messytable-slow-vol/messy-table-dataset/rand_scenes/train_list.txt"
      LEFT_NAME: "1024_irL_real_360.png"
      RIGHT_NAME: "1024_irR_real_360.png"
      LEFT_PATTERN_NAME: "1024_irL_real_360.png"
      RIGHT_PATTERN_NAME: "1024_irR_real_360.png"
  VAL:
    SIM:
      ROOT_DIR: "/messytable-slow-vol/messy-table-dataset/v12_sample/training"
      SPLIT_FILE: "/messytable-slow-vol/messy-table-dataset/v12_sample/training_lists/all_val.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "0128_irL_kuafu_half.png"
      RIGHT_NAME: "0128_irR_kuafu_half.png"
      LEFT_PATTERN_NAME: "0128_irL_kuafu_half.png"
      RIGHT_PATTERN_NAME: "0128_irR_kuafu_half.png"
  TEST:
    REAL:
      ROOT_DIR: "/messytable-slow-vol/messy-table-dataset/real_data_v10/"
      SPLIT_FILE: "/messytable-slow-vol/messy-table-dataset/real_data_v10/test_list.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "1024_irL_real.png"
      RIGHT_NAME: "1024_irR_real.png"
      LABEL_NAME: "irL_label_image.png"
      NORMAL_NAME: "normalL.png"
      HEIGHT: 544
      WIDTH: 960
    SIM:
      ROOT_DIR: "/messytable-slow-vol/messy-table-dataset/v12_sample/training"
      SPLIT_FILE: "/messytable-slow-vol/messy-table-dataset/v12_sample/training_lists/all_val.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "0128_irL_kuafu_half.png"
      RIGHT_NAME: "0128_irR_kuafu_half.png"
      HEIGHT: 544
      WIDTH: 960
MODEL_TYPE: "SMDNet"
OPTIMIZER:
  TYPE: "Adam"
  LR: 1e-4
LR_SCHEDULER:
  TYPE: 'StepLR'
  StepLR:
    step_size: 20000
    gamma: 0.7
TRAIN:
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  LOG_PERIOD: 10
  CHECKPOINT_PERIOD: 5000
  MAX_TO_KEEP: 2
  MAX_ITER: 10000
VAL:
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  PERIOD: 10
  LOG_PERIOD: 10
LOSS:
  SIM_DISP:
    WEIGHT: 1.0
  SIM_REPROJ:
    WEIGHT: 0.0
  REAL_REPROJ:
    WEIGHT: 0.0
SMDNet:
  NUM_SAMPLES: 50000
  NO_SINE: True
  NO_RESIDUAL: True
    
TEST:
  NUM_WORKERS: 0
  MAX_DISP: 192
  WEIGHT: "/edward-slow-vol/checkpoints/smd_activezero2/model_010000.pth"
